
built-in-y += atbm_os_api.o atbm_os_atomic.o atbm_os_mem.o atbm_os_mutex.o \
	atbm_os_sdio.o atbm_os_skbuf.o atbm_os_spinlock.o atbm_os_thread.o \
	atbm_os_timer.o atbm_os_usb.o atbm_os_workqueue.o

obj-y += built-in.o
